/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pelu;

import javax.swing.JOptionPane;

/**
 *
 * @author JORGE
 */
public class Interfaz extends javax.swing.JFrame {

    Ana elemento1 = new Ana();
    Ana elemento2 = new Ana();
    Ana elemento3 = new Ana();
    Ana elemento4 = new Ana();
    Jose elemento5 = new Jose();
    Jose elemento6 = new Jose();
    Jose elemento7 = new Jose();
    Jose elemento8 = new Jose();
    Roberto elemento9 = new Roberto();
    Roberto elemento10 = new Roberto();
    Roberto elemento11 = new Roberto();
    Roberto elemento12 = new Roberto();
    Lucrecia elemento13 = new Lucrecia();
    Lucrecia elemento14 = new Lucrecia();
    Lucrecia elemento15 = new Lucrecia();
    Lucrecia elemento16 = new Lucrecia();
    
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        dineroTotalRoberto = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        valorRoberto1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        valorRoberto2 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        valorRoberto3 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        valorRoberto4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        valorTotalRoberto = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        dineroRoberto1 = new javax.swing.JLabel();
        valorAna1 = new javax.swing.JLabel();
        dineroRoberto2 = new javax.swing.JLabel();
        valorAna2 = new javax.swing.JLabel();
        valorAna3 = new javax.swing.JLabel();
        valorAna4 = new javax.swing.JLabel();
        valorLucrecia2 = new javax.swing.JLabel();
        valorTotalAna = new javax.swing.JLabel();
        dineroAna1 = new javax.swing.JLabel();
        dineroAna2 = new javax.swing.JLabel();
        dineroAna3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        valorLucrecia3 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        dineroAna4 = new javax.swing.JLabel();
        valorLucrecia4 = new javax.swing.JLabel();
        dineroTotalAna = new javax.swing.JLabel();
        valorTotalLucrecia = new javax.swing.JLabel();
        dineroJose3 = new javax.swing.JLabel();
        dineroLucrecia1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        dineroLucrecia2 = new javax.swing.JLabel();
        dineroJose4 = new javax.swing.JLabel();
        dineroLucrecia3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        dineroTotalJose = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        valorJose1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        dineroLucrecia4 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        dineroTotalLucrecia = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        valorJose2 = new javax.swing.JLabel();
        valorLucrecia1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        valorJose3 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        iniciarDia = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        registrarAna = new javax.swing.JButton();
        valorJose4 = new javax.swing.JLabel();
        registrarRoberto = new javax.swing.JButton();
        valorTotalJose = new javax.swing.JLabel();
        dineroJose1 = new javax.swing.JLabel();
        dineroJose2 = new javax.swing.JLabel();
        registrarLucrecia = new javax.swing.JButton();
        registrarJose = new javax.swing.JButton();
        total_Final = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        dineroRoberto3 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        dineroRoberto4 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();

        jLabel54.setText("$");

        jLabel55.setText("$");

        jLabel56.setText("$");

        jLabel57.setText("$");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 43, 136));

        dineroTotalRoberto.setText("0");

        jLabel38.setIcon(new javax.swing.ImageIcon("C:\\Users\\JORGE\\OneDrive\\Documentos\\Programacion 2\\img 4.jpg")); // NOI18N

        jLabel22.setText("Corte dama:         ");

        jLabel39.setIcon(new javax.swing.ImageIcon("C:\\Users\\JORGE\\OneDrive\\Documentos\\Programacion 2\\img 2.jpg")); // NOI18N

        valorRoberto1.setText("0");

        jLabel23.setText("Tintura cabello:   ");

        valorRoberto2.setText("0");

        jLabel24.setText("Peinado:               ");

        jLabel40.setIcon(new javax.swing.ImageIcon("C:\\Users\\JORGE\\OneDrive\\Documentos\\Programacion 2\\img 3.jpg")); // NOI18N

        jLabel41.setIcon(new javax.swing.ImageIcon("C:\\Users\\JORGE\\OneDrive\\Documentos\\Programacion 2\\img 1.jpg")); // NOI18N

        valorRoberto3.setText("0");

        jLabel25.setText("Total de servicios:  ");

        jLabel26.setText("Total recaudado:  ");

        valorRoberto4.setText("0");

        jLabel10.setText("Total de servicios:  ");

        valorTotalRoberto.setText("0");

        jLabel11.setText("Total recaudado:  ");

        dineroRoberto1.setText("0.00");

        valorAna1.setText("0");

        dineroRoberto2.setText("0.00");

        valorAna2.setText("0");

        valorAna3.setText("0");

        valorAna4.setText("0");

        valorLucrecia2.setText("0");

        valorTotalAna.setText("0");

        dineroAna1.setText("0.00");

        dineroAna2.setText("0.00");

        dineroAna3.setText("0.00");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("Ana");

        jLabel6.setText("Corte caballero: ");

        jLabel7.setText("Corte dama:         ");

        jLabel8.setText("Tintura cabello:   ");

        jLabel9.setText("Peinado:               ");

        jLabel29.setText("Peinado:               ");

        valorLucrecia3.setText("0");

        jLabel30.setText("Total de servicios:  ");

        jLabel31.setText("Total recaudado:  ");

        dineroAna4.setText("0.00");

        valorLucrecia4.setText("0");

        dineroTotalAna.setText("0");

        valorTotalLucrecia.setText("0");

        dineroJose3.setText("0.00");

        dineroLucrecia1.setText("0.00");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 153));
        jLabel12.setText("José");

        dineroLucrecia2.setText("0.00");

        dineroJose4.setText("0.00");

        dineroLucrecia3.setText("0.00");

        jLabel13.setText("Corte caballero: ");

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 153));
        jLabel32.setText("Lucrecia");

        dineroTotalJose.setText("0");

        jLabel14.setText("Corte dama:         ");

        valorJose1.setText("0");

        jLabel15.setText("Tintura cabello:   ");

        dineroLucrecia4.setText("0.00");

        jLabel33.setText("Corte caballero: ");

        dineroTotalLucrecia.setText("0");

        jLabel34.setText("Corte dama:         ");

        valorJose2.setText("0");

        valorLucrecia1.setText("0");

        jLabel16.setText("Peinado:               ");

        jLabel35.setText("Tintura cabello:   ");

        valorJose3.setText("0");

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 153));
        jLabel36.setText("Sistema de control");

        jLabel17.setText("Total de servicios:  ");

        iniciarDia.setText("Iniciar Día");
        iniciarDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarDiaActionPerformed(evt);
            }
        });

        jLabel18.setText("Total recaudado:  ");

        registrarAna.setText("Registrar Ana");
        registrarAna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarAnaActionPerformed(evt);
            }
        });

        valorJose4.setText("0");

        registrarRoberto.setText("Registrar Roberto");
        registrarRoberto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarRobertoActionPerformed(evt);
            }
        });

        valorTotalJose.setText("0");

        dineroJose1.setText("0.00");

        dineroJose2.setText("0.00");

        registrarLucrecia.setText("Registrar Lucrecia");
        registrarLucrecia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarLucreciaActionPerformed(evt);
            }
        });

        registrarJose.setText("Registrar José");
        registrarJose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarJoseActionPerformed(evt);
            }
        });

        total_Final.setText("Ver Totales");
        total_Final.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_FinalActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        dineroRoberto3.setText("0.00");

        jLabel37.setBackground(new java.awt.Color(102, 204, 255));
        jLabel37.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(102, 102, 102));
        jLabel37.setText("Creative Cuts Studio");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 153));
        jLabel20.setText("Roberto");

        dineroRoberto4.setText("0.00");

        jLabel21.setText("Corte caballero: ");

        jLabel2.setText("$");

        jLabel3.setText("$");

        jLabel4.setText("$");

        jLabel19.setText("$");

        jLabel27.setText("$");

        jLabel42.setIcon(new javax.swing.ImageIcon("C:\\Users\\JORGE\\OneDrive\\Documentos\\Programacion 2\\logo.jpg")); // NOI18N

        jLabel28.setText("$");

        jLabel43.setText("$");

        jLabel44.setText("$");

        jLabel45.setText("$");

        jLabel46.setText("$");

        jLabel47.setText("$");

        jLabel48.setText("$");

        jLabel49.setText("$");

        jLabel50.setText("$");

        jLabel51.setText("$");

        jLabel52.setText("$");

        jLabel53.setText("$");

        jLabel58.setText("$");

        jLabel59.setText("$");

        jLabel60.setText("$");

        jLabel61.setText("$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel41)
                            .addComponent(jLabel38))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(dineroTotalAna))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel5)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel9)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(valorAna4))
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel7)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(valorAna2))
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel6)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(valorAna1))
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addGap(93, 93, 93)
                                                                .addComponent(jLabel27)))
                                                        .addGap(1, 1, 1))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel8)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(valorAna3)))
                                                .addGap(14, 14, 14)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel28)
                                                    .addComponent(jLabel43)
                                                    .addComponent(jLabel44)
                                                    .addComponent(jLabel45)))
                                            .addComponent(jLabel50, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel51, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel52, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel53, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dineroAna1)
                                            .addComponent(dineroAna2)
                                            .addComponent(dineroAna3)
                                            .addComponent(dineroAna4)
                                            .addComponent(dineroRoberto1)
                                            .addComponent(dineroRoberto2)
                                            .addComponent(dineroRoberto3)
                                            .addComponent(dineroRoberto4)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(valorTotalAna)))
                                .addGap(42, 42, 42)
                                .addComponent(jLabel40)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(valorTotalJose))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dineroTotalJose))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel12)
                                                    .addGap(87, 87, 87))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel15)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(valorJose3)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel16)
                                                .addGap(18, 18, 18)
                                                .addComponent(valorJose4))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addGap(18, 18, 18)
                                                .addComponent(valorJose1))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(valorJose2)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel46)
                                            .addComponent(jLabel47)
                                            .addComponent(jLabel48)
                                            .addComponent(jLabel49))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dineroJose1)
                                            .addComponent(dineroJose2)
                                            .addComponent(dineroJose3)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(dineroJose4))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(196, 196, 196)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel20)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel24)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(valorRoberto4))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel21)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(valorRoberto1))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel22)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(valorRoberto2)))
                                            .addGap(1, 1, 1))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel23)
                                            .addGap(18, 18, 18)
                                            .addComponent(valorRoberto3)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dineroTotalRoberto))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(valorTotalRoberto)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel39)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel31)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dineroTotalLucrecia))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel32)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel29)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(valorLucrecia4))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel30)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(valorTotalLucrecia))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel33)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(valorLucrecia1))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel34)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(valorLucrecia2)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel35)
                                                .addGap(18, 18, 18)
                                                .addComponent(valorLucrecia3)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel58)
                                            .addComponent(jLabel59)
                                            .addComponent(jLabel60)
                                            .addComponent(jLabel61))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dineroLucrecia1)
                                            .addComponent(dineroLucrecia2)
                                            .addComponent(dineroLucrecia3)
                                            .addComponent(dineroLucrecia4)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(iniciarDia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(registrarAna)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(registrarRoberto)
                        .addGap(12, 12, 12)
                        .addComponent(registrarJose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(registrarLucrecia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(total_Final)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(salir))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel36)))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel37)
                .addGap(237, 237, 237))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(jLabel42))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(30, 30, 30)
                                            .addComponent(jLabel37)))
                                    .addGap(9, 9, 9)
                                    .addComponent(jLabel40))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(123, 123, 123)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(valorAna1)
                                        .addComponent(dineroAna1)
                                        .addComponent(jLabel28))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(valorAna2)
                                        .addComponent(dineroAna2)
                                        .addComponent(jLabel43))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(valorAna3)
                                        .addComponent(jLabel8)
                                        .addComponent(dineroAna3)
                                        .addComponent(jLabel44))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(valorAna4)
                                        .addComponent(dineroAna4)
                                        .addComponent(jLabel45))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel10)
                                        .addComponent(valorTotalAna))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel11)
                                        .addComponent(dineroTotalAna)
                                        .addComponent(jLabel27))))
                            .addGap(61, 61, 61))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(120, 120, 120)
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel13)
                                        .addComponent(valorJose1))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel14)
                                        .addComponent(valorJose2))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(valorJose3)
                                        .addComponent(jLabel15))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel16)
                                        .addComponent(valorJose4)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(dineroJose1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dineroJose2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dineroJose3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dineroJose4))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel46)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel47)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel48)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel49)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel17)
                                .addComponent(valorTotalJose))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18)
                                .addComponent(dineroTotalJose)
                                .addComponent(jLabel3))
                            .addGap(87, 87, 87)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel41)
                        .addGap(60, 60, 60)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38)
                    .addComponent(jLabel39)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(valorRoberto1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(valorRoberto2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(valorRoberto3)
                                    .addComponent(jLabel23))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel24)
                                    .addComponent(valorRoberto4)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dineroRoberto1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dineroRoberto2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dineroRoberto3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dineroRoberto4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel50)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel51)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel52)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel53)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(valorTotalRoberto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dineroTotalRoberto)
                            .addComponent(jLabel4)
                            .addComponent(jLabel26)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel33)
                                    .addComponent(valorLucrecia1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel34)
                                    .addComponent(valorLucrecia2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(valorLucrecia3)
                                    .addComponent(jLabel35))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel29)
                                    .addComponent(valorLucrecia4)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dineroLucrecia1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dineroLucrecia2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dineroLucrecia3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dineroLucrecia4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel58)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel59)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel60)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel61)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(valorTotalLucrecia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dineroTotalLucrecia)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel31)
                                .addComponent(jLabel19)))))
                .addGap(18, 18, 18)
                .addComponent(jLabel36)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iniciarDia)
                    .addComponent(registrarAna)
                    .addComponent(registrarRoberto)
                    .addComponent(registrarLucrecia)
                    .addComponent(total_Final)
                    .addComponent(salir)
                    .addComponent(registrarJose))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarDiaActionPerformed
        elemento1 = new Ana();
        dineroAna1.setText(String.valueOf(elemento1.resultado));
        valorAna1.setText(String.valueOf(elemento1.cantidad));
        elemento2 = new Ana();
        dineroAna2.setText(String.valueOf(elemento2.resultado));
        valorAna2.setText(String.valueOf(elemento2.cantidad));
        elemento3 = new Ana();
        dineroAna3.setText(String.valueOf(elemento3.resultado));
        valorAna3.setText(String.valueOf(elemento3.cantidad));
        elemento4 = new Ana();
        dineroAna4.setText(String.valueOf(elemento4.resultado));
        valorAna4.setText(String.valueOf(elemento4.cantidad));
        dineroTotalAna.setText(String.valueOf(0));
        valorTotalAna.setText(String.valueOf(0));
        
        elemento5 = new Jose();
        dineroJose1.setText(String.valueOf(elemento5.resultado));
        valorJose1.setText(String.valueOf(elemento5.cantidad));
        elemento6 = new Jose();
        dineroJose2.setText(String.valueOf(elemento6.resultado));
        valorJose2.setText(String.valueOf(elemento6.cantidad));
        elemento7 = new Jose();
        dineroJose3.setText(String.valueOf(elemento7.resultado));
        valorJose3.setText(String.valueOf(elemento7.cantidad));
        elemento8 = new Jose();
        dineroJose4.setText(String.valueOf(elemento8.resultado));
        valorJose4.setText(String.valueOf(elemento8.cantidad));
        dineroTotalJose.setText(String.valueOf(0));
        valorTotalJose.setText(String.valueOf(0));
        
        elemento9 = new Roberto();
        dineroRoberto1.setText(String.valueOf(elemento9.resultado));
        valorRoberto1.setText(String.valueOf(elemento9.cantidad));
        elemento10 = new Roberto();
        dineroRoberto2.setText(String.valueOf(elemento10.resultado));
        valorRoberto2.setText(String.valueOf(elemento10.cantidad));
        elemento11 = new Roberto();
        dineroRoberto3.setText(String.valueOf(elemento11.resultado));
        valorRoberto3.setText(String.valueOf(elemento11.cantidad));
        elemento12 = new Roberto();
        dineroRoberto4.setText(String.valueOf(elemento12.resultado));
        valorRoberto4.setText(String.valueOf(elemento12.cantidad));
        dineroTotalRoberto.setText(String.valueOf(0));
        valorTotalRoberto.setText(String.valueOf(0));
        
        elemento13 = new Lucrecia();
        dineroLucrecia1.setText(String.valueOf(elemento13.resultado));
        valorLucrecia1.setText(String.valueOf(elemento13.cantidad));
        elemento14 = new Lucrecia();
        dineroLucrecia2.setText(String.valueOf(elemento14.resultado));
        valorLucrecia2.setText(String.valueOf(elemento14.cantidad));
        elemento15 = new Lucrecia();
        dineroLucrecia3.setText(String.valueOf(elemento15.resultado));
        valorLucrecia3.setText(String.valueOf(elemento15.cantidad));
        elemento16 = new Lucrecia();
        dineroLucrecia4.setText(String.valueOf(elemento16.resultado));
        valorLucrecia4.setText(String.valueOf(elemento16.cantidad));
        dineroTotalLucrecia.setText(String.valueOf(0));
        valorTotalLucrecia.setText(String.valueOf(0));
    }//GEN-LAST:event_iniciarDiaActionPerformed

    private void registrarAnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarAnaActionPerformed
        String [] arreglo = {"Corte caballero", "Corte dama", "Tintura", "Peinado"};
        int opcion = JOptionPane.showOptionDialog(rootPane, "Registrar Ana", "Elige una opción", 0, JOptionPane.QUESTION_MESSAGE, null, arreglo, null);
        if (opcion ==0){
            elemento1.corteCaballero();
            dineroAna1.setText(String.valueOf(elemento1.resultado));
            valorAna1.setText(String.valueOf(elemento1.cantidad));
        }
        if (opcion ==1){
            elemento2.corteDama();
            dineroAna2.setText(String.valueOf(elemento2.resultado));
            valorAna2.setText(String.valueOf(elemento2.cantidad));
        }
        if (opcion ==2){
            elemento3.tintura();
            dineroAna3.setText(String.valueOf(elemento3.resultado));
            valorAna3.setText(String.valueOf(elemento3.cantidad));
        }
        if (opcion ==3){
            elemento4.peinado();
            dineroAna4.setText(String.valueOf(elemento4.resultado));
            valorAna4.setText(String.valueOf(elemento4.cantidad));
        }
        
        
    }//GEN-LAST:event_registrarAnaActionPerformed

    private void registrarRobertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarRobertoActionPerformed
        String [] arreglo = {"Corte caballero", "Corte dama", "Tintura", "Peinado"};
        int opcion = JOptionPane.showOptionDialog(rootPane, "Registrar Roberto", "Elige una opción", 0, JOptionPane.QUESTION_MESSAGE, null, arreglo, null);
        if (opcion ==0){
            elemento9.corteCaballero();
            dineroRoberto1.setText(String.valueOf(elemento9.resultado));
            valorRoberto1.setText(String.valueOf(elemento9.cantidad));
        }
        if (opcion ==1){
            elemento10.corteDama();
            dineroRoberto2.setText(String.valueOf(elemento10.resultado));
            valorRoberto2.setText(String.valueOf(elemento10.cantidad));
        }
        if (opcion ==2){
            elemento11.tintura();
            dineroRoberto3.setText(String.valueOf(elemento11.resultado));
            valorRoberto3.setText(String.valueOf(elemento11.cantidad));
        }
        if (opcion ==3){
            elemento12.peinado();
            dineroRoberto4.setText(String.valueOf(elemento12.resultado));
            valorRoberto4.setText(String.valueOf(elemento12.cantidad));
        }
    }//GEN-LAST:event_registrarRobertoActionPerformed

    private void registrarJoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarJoseActionPerformed
        String [] arreglo = {"Corte caballero", "Corte dama", "Tintura", "Peinado"};
        int opcion = JOptionPane.showOptionDialog(rootPane, "Registrar Jose", "Elige una opción", 0, JOptionPane.QUESTION_MESSAGE, null, arreglo, null);
        if (opcion ==0){
            elemento5.corteCaballero();
            dineroJose1.setText(String.valueOf(elemento5.resultado));
            valorJose1.setText(String.valueOf(elemento5.cantidad));
        }
        if (opcion ==1){
            elemento6.corteDama();
            dineroJose2.setText(String.valueOf(elemento6.resultado));
            valorJose2.setText(String.valueOf(elemento6.cantidad));
        }
        if (opcion ==2){
            elemento7.tintura();
            dineroJose3.setText(String.valueOf(elemento7.resultado));
            valorJose3.setText(String.valueOf(elemento7.cantidad));
        }
        if (opcion ==3){
            elemento8.peinado();
            dineroJose4.setText(String.valueOf(elemento8.resultado));
            valorJose4.setText(String.valueOf(elemento8.cantidad));
        }
    }//GEN-LAST:event_registrarJoseActionPerformed

    private void total_FinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_FinalActionPerformed
        dineroTotalAna.setText(String.valueOf(elemento1.resultado+elemento2.resultado+elemento3.resultado+elemento4.resultado));
        valorTotalAna.setText(String.valueOf(elemento1.cantidad+elemento2.cantidad+elemento3.cantidad+elemento4.cantidad));
        
        dineroTotalJose.setText(String.valueOf(elemento5.resultado+elemento6.resultado+elemento7.resultado+elemento8.resultado));
        valorTotalJose.setText(String.valueOf(elemento5.cantidad+elemento6.cantidad+elemento7.cantidad+elemento8.cantidad));
        
        dineroTotalRoberto.setText(String.valueOf(elemento9.resultado+elemento10.resultado+elemento11.resultado+elemento12.resultado));
        valorTotalRoberto.setText(String.valueOf(elemento9.cantidad+elemento10.cantidad+elemento11.cantidad+elemento12.cantidad));
        
        dineroTotalLucrecia.setText(String.valueOf(elemento13.resultado+elemento14.resultado+elemento15.resultado+elemento16.resultado));
        valorTotalLucrecia.setText(String.valueOf(elemento13.cantidad+elemento14.cantidad+elemento15.cantidad+elemento16.cantidad));
        
    }//GEN-LAST:event_total_FinalActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        int totalDinero = Integer.parseInt(dineroTotalAna.getText()) + Integer.parseInt(dineroTotalJose.getText()) + Integer.parseInt(dineroTotalRoberto.getText()) + Integer.parseInt(dineroTotalLucrecia.getText());
        int servicios = Integer.parseInt(valorTotalAna.getText()) + Integer.parseInt(valorTotalJose.getText()) + Integer.parseInt(valorTotalRoberto.getText()) + Integer.parseInt(valorTotalLucrecia.getText());
        JOptionPane.showMessageDialog(rootPane, "Total de servicios es: " + servicios);
        JOptionPane.showMessageDialog(rootPane, "El total recaudado en el dia es: " + totalDinero);
        JOptionPane.showMessageDialog(rootPane, "Fin del programa");
        
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void registrarLucreciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarLucreciaActionPerformed
        String [] arreglo = {"Corte caballero", "Corte dama", "Tintura", "Peinado"};
        int opcion = JOptionPane.showOptionDialog(rootPane, "Registrar Lucrecia", "Elige una opción", 0, JOptionPane.QUESTION_MESSAGE, null, arreglo, null);
        if (opcion ==0){
            elemento13.corteCaballero();
            dineroLucrecia1.setText(String.valueOf(elemento13.resultado));
            valorLucrecia1.setText(String.valueOf(elemento13.cantidad));
        }
        if (opcion ==1){
            elemento14.corteDama();
            dineroLucrecia2.setText(String.valueOf(elemento14.resultado));
            valorLucrecia2.setText(String.valueOf(elemento14.cantidad));
        }
        if (opcion ==2){
            elemento15.tintura();
            dineroLucrecia3.setText(String.valueOf(elemento15.resultado));
            valorLucrecia3.setText(String.valueOf(elemento15.cantidad));
        }
        if (opcion ==3){
            elemento16.peinado();
            dineroLucrecia4.setText(String.valueOf(elemento16.resultado));
            valorLucrecia4.setText(String.valueOf(elemento16.cantidad));
        }
    }//GEN-LAST:event_registrarLucreciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dineroAna1;
    private javax.swing.JLabel dineroAna2;
    private javax.swing.JLabel dineroAna3;
    private javax.swing.JLabel dineroAna4;
    private javax.swing.JLabel dineroJose1;
    private javax.swing.JLabel dineroJose2;
    private javax.swing.JLabel dineroJose3;
    private javax.swing.JLabel dineroJose4;
    private javax.swing.JLabel dineroLucrecia1;
    private javax.swing.JLabel dineroLucrecia2;
    private javax.swing.JLabel dineroLucrecia3;
    private javax.swing.JLabel dineroLucrecia4;
    private javax.swing.JLabel dineroRoberto1;
    private javax.swing.JLabel dineroRoberto2;
    private javax.swing.JLabel dineroRoberto3;
    private javax.swing.JLabel dineroRoberto4;
    private javax.swing.JLabel dineroTotalAna;
    private javax.swing.JLabel dineroTotalJose;
    private javax.swing.JLabel dineroTotalLucrecia;
    private javax.swing.JLabel dineroTotalRoberto;
    private javax.swing.JButton iniciarDia;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton registrarAna;
    private javax.swing.JButton registrarJose;
    private javax.swing.JButton registrarLucrecia;
    private javax.swing.JButton registrarRoberto;
    private javax.swing.JButton salir;
    private javax.swing.JButton total_Final;
    private javax.swing.JLabel valorAna1;
    private javax.swing.JLabel valorAna2;
    private javax.swing.JLabel valorAna3;
    private javax.swing.JLabel valorAna4;
    private javax.swing.JLabel valorJose1;
    private javax.swing.JLabel valorJose2;
    private javax.swing.JLabel valorJose3;
    private javax.swing.JLabel valorJose4;
    private javax.swing.JLabel valorLucrecia1;
    private javax.swing.JLabel valorLucrecia2;
    private javax.swing.JLabel valorLucrecia3;
    private javax.swing.JLabel valorLucrecia4;
    private javax.swing.JLabel valorRoberto1;
    private javax.swing.JLabel valorRoberto2;
    private javax.swing.JLabel valorRoberto3;
    private javax.swing.JLabel valorRoberto4;
    private javax.swing.JLabel valorTotalAna;
    private javax.swing.JLabel valorTotalJose;
    private javax.swing.JLabel valorTotalLucrecia;
    private javax.swing.JLabel valorTotalRoberto;
    // End of variables declaration//GEN-END:variables
}
